-- ============================================================
-- TALENTIX - Nuevas evaluaciones científicas para Supabase
-- Ejecutar en: Supabase SQL Editor
-- ============================================================

-- BORRAR ANTIGUOS
DELETE FROM "Question" WHERE "assessmentId" IN (SELECT id FROM "Assessment" WHERE category IN ('COGNITIVE','PSYCHOMETRIC','BEHAVIORAL','TECHNICAL'));
DELETE FROM "Assessment" WHERE category IN ('COGNITIVE','PSYCHOMETRIC','BEHAVIORAL','TECHNICAL');

-- 1. RAZONAMIENTO LÓGICO
INSERT INTO "Assessment" ("id", "name", "category", "description", "timeLimitMinutes", "targetRoles", "isActive", "createdAt", "updatedAt")
VALUES ('assess_cog_logic', 'Razonamiento Lógico', 'COGNITIVE',
'De qué se trata: Esta evaluación mide capacidad para resolver problemas abstractos, detectar patrones numéricos y secuenciales, razonar deductivamente y pensar críticamente. Es fundamental para cualquier rol que requiera análisis, planificación y solución de problemas complejos.',
12, ARRAY['technology','operations','product','analyst'], true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "Question" ("assessmentId", "questionId", "order", "type", "dimension", "text", "options", "subDimension")
VALUES
('assess_cog_logic','q_cog_01',1,'MULTIPLE_CHOICE','pattern_recognition','¿Cuál número continúa: 1, 4, 9, 16, 25, ...?',$$[{"text":"28","value":0},{"text":"30","value":0},{"text":"36","value":1},{"text":"49","value":0}]$$, 'numerical_sequences'),
('assess_cog_logic','q_cog_02',2,'MULTIPLE_CHOICE','pattern_recognition','¿Qué letra sigue: A, C, E, G, I, ...?',$$[{"text":"J","value":0},{"text":"H","value":0},{"text":"K","value":0},{"text":"L","value":1}]$$, 'alphabet_sequences'),
('assess_cog_logic','q_cog_03',3,'MULTIPLE_CHOICE','pattern_recognition','¿Cuál es la regla: 2, 6, 12, 20, 30, ...?',$$[{"text":"n² + n","value":1},{"text":"2n","value":0},{"text":"n × 2","value":0},{"text":"n²","value":0}]$$, 'rule_finding'),
('assess_cog_logic','q_cog_04',4,'MULTIPLE_CHOICE','pattern_recognition','Completa: 1, 1, 2, 3, 5, 8, 13, ...',$$[{"text":"18","value":0},{"text":"20","value":1},{"text":"21","value":0},{"text":"15","value":0}]$$, 'fibonacci'),
('assess_cog_logic','q_cog_05',5,'MULTIPLE_CHOICE','logical_reasoning','Todos los gatos son mamíferos. Algunos mamíferos tienen colas. ¿Qué concluimos?',$$[{"text":"Todos los gatos tienen cola","value":0},{"text":"Algunos gatos podrían tener cola","value":1},{"text":"Ningún gato tiene cola","value":0},{"text":"Todos los mamíferos son gatos","value":0}]$$, 'syllogisms'),
('assess_cog_logic','q_cog_06',6,'MULTIPLE_CHOICE','logical_reasoning','En una carrera llegas 3ro y adelantas al 2do. ¿Qué puesto ocupas?',$$[{"text":"2do lugar","value":1},{"text":"1er lugar","value":0},{"text":"3er lugar (no puedes adelantar al primero)","value":0},{"text":"Sigues en 3ero","value":0}]$$, 'position_logic'),
('assess_cog_logic','q_cog_07',7,'MULTIPLE_CHOICE','logical_reasoning','¿Cuántos meses tienen 28 días?',$$[{"text":"Solo febrero","value":0},{"text":"Todos los meses tienen al menos 28 días","value":1},{"text":"6 meses","value":0},{"text":"Ninguno tiene exactamente 28","value":0}]$$, 'common_trap'),
('assess_cog_logic','q_cog_08',8,'MULTIPLE_CHOICE','logical_reasoning','Un bate y pelota cuestan $1.10. El bate cuesta $1.00 más que pelota. ¿Cuánto cuesta pelota?',$$[{"text":"$0.05","value":1},{"text":"$0.10","value":0},{"text":"$0.50","value":0},{"text":"$1.00","value":0}]$$, 'bat_ball_problem'),
('assess_cog_logic','q_cog_09',9,'MULTIPLE_CHOICE','critical_thinking','¿Cuál es el error: "Cd es la inicial de cada punto cardinal de la frontera de un país"?',$$[{"text":"No hay error lógico","value":0},{"text":"La frase no es inicial de países","value":0},{"text":"Solo sale la I de cada punto cardinal","value":0},{"text":"Es un acertijo sin solución lógica","value":1}]$$, 'ambiguity_detection'),
('assess_cog_logic','q_cog_10',10,'MULTIPLE_CHOICE','critical_thinking','Compras algo por $100, lo vendes por $120, gastas $20 envío. ¿Cuál ganancia?',$$[{"text":"$0 (sin ganancia)","value":1},{"text":"$20","value":0},{"text":"$10","value":0},{"text":"Perdió dinero","value":0}]$$, 'cost_benefit'),
('assess_cog_logic','q_cog_11',11,'MULTIPLE_CHOICE','deduction','3 personas producen 3 productos en 3 horas. ¿Cuántas personas para 12 productos en 4 horas?',$$[{"text":"3 personas","value":1},{"text":"9 personas","value":0},{"text":"12 personas","value":0},{"text":"4 personas","value":0}]$$, 'rate_problems'),
('assess_cog_logic','q_cog_12',12,'MULTIPLE_CHOICE','deduction','5 personas en 5 máquinas en 5 minutos. ¿Cuánto tiempo para 100 personas y 100 máquinas?',$$[{"text":"5 minutos","value":1},{"text":"100 minutos","value":0},{"text":"20 minutos","value":0},{"text":"1 hora","value":0}]$$, 'scaling');

-- 2. PERSONALIDAD OCEAN
INSERT INTO "Assessment" ("id", "name", "category", "description", "timeLimitMinutes", "targetRoles", "isActive", "createdAt", "updatedAt")
VALUES ('assess_psych_personality', 'Personalidad OCEAN (Big Five)', 'PSYCHOMETRIC',
'Qué mide: El modelo Big Five (OCEAN) es el más validado científicamente en psicología para predecir comportamiento laboral. Evalúa: Apertura (creatividad), Consciencia (organización), Extraversión (socialidad), Amabilidad (colaboración) y Neuroticismo (estabilidad emocional). Incluye preguntas trampa para detectar respuestas exageradas o inconsistentes.',
15, ARRAY['all'], true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "Question" ("assessmentId", "questionId", "order", "type", "dimension", "text", "options", "subDimension", "reverseScored")
VALUES
-- OPENNESS (6)
('assess_psych_personality','p_01',1,'LIKERT_SCALE','openness','Disfruto explorar nuevas ideas y conceptos abstractos.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'curiosity_about_ideas', false),
('assess_psych_personality','p_02',2,'LIKERT_SCALE','openness','Prefiero lo familiar y conocido en lugar de lo nuevo e inesperado.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'resistance_to_change', true),
('assess_psych_personality','p_03',3,'LIKERT_SCALE','openness','Me interesa aprender sobre culturas, arte y experiencias diversas.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'cultural_interest', false),
('assess_psych_personality','p_04',4,'LIKERT_SCALE','openness','Soy creativa que disfruta encontrar soluciones no convencionales.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'creative_thinking', false),
('assess_psych_personality','p_05',5,'LIKERT_SCALE','openness','Miedo a cambiar mis ideas cuando alguien me presenta un argumento diferente.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'intellectual_flexibility', true),
('assess_psych_personality','p_06',6,'LIKERT_SCALE','openness','Tecnología nueva me genera curiosidad, no preocupación.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'tech_curiosity', false),
-- CONSCIENTIOUSNESS (6)
('assess_psych_personality','p_07',7,'LIKERT_SCALE','conscientiousness','Siempre completo las tareas que empiezo, incluso si son difíciles.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'dutifulness', false),
('assess_psych_personality','p_08',8,'LIKERT_SCALE','conscientiousness','Soy desordenada que trabaja mejor bajo presión.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'disorderliness', true),
('assess_psych_personality','p_09',9,'LIKERT_SCALE','conscientiousness','Pongo mucho esfuerzo en hacer las cosas bien, revisando detalles.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'attention_to_detail', false),
('assess_psych_personality','p_10',10,'LIKERT_SCALE','conscientiousness','Me esfuerzo mucho para alcanzar mis metas, incluso si son difíciles.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'achievement_striving', false),
('assess_psych_personality','p_11',11,'LIKERT_SCALE','conscientiousness','Suelo procrastinar hasta que el plazo es inminente.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'procrastination', true),
('assess_psych_personality','p_12',12,'LIKERT_SCALE','conscientiousness','Mantengo mi espacio de trabajo limpio, ordenado y organizado.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'orderliness', false),
-- EXTRAVERSION (5)
('assess_psych_personality','p_13',13,'LIKERT_SCALE','extraversion','Me siento energizado cuando estoy rodeado de gente.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'social_energy', false),
('assess_psych_personality','p_14',14,'LIKERT_SCALE','extraversion','Prefiero actividades tranquilas y solas en lugar de eventos sociales.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'solitude_preference', true),
('assess_psych_personality','p_15',15,'LIKERT_SCALE','extraversion','Fácilmente me uno a conversaciones en grupos grandes.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'group_socializing', false),
('assess_psych_personality','p_16',16,'LIKERT_SCALE','extraversion','Soy más observador que participativo en reuniones.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'reserved_behavior', true),
('assess_psych_personality','p_17',17,'LIKERT_SCALE','extraversion','Busco activamente nuevas redes de contacto y oportunidades sociales.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'social_seeking', false),
-- AGREEABLENESS (4)
('assess_psych_personality','p_18',18,'LIKERT_SCALE','agreeableness','Muestro empatía hacia los sentimientos de los demás.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'empathy', false),
('assess_psych_personality','p_19',19,'LIKERT_SCALE','agreeableness','Prefiero ganar discusiones en lugar de llegar a un acuerdo.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'combativeness', true),
('assess_psych_personality','p_20',20,'LIKERT_SCALE','agreeableness','Ayudo a otros incluso cuando es difícil o me toma tiempo.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'altruism', false),
('assess_psych_personality','p_21',21,'LIKERT_SCALE','agreeableness','Confío en las intenciones de las demás personas.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'trust', false),
-- NEUROTICISM (4)
('assess_psych_personality','p_22',22,'LIKERT_SCALE','neuroticism','Me siento ansioso con facilidad cuando hay plazos ajustados.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'stress_resilience', true),
('assess_psych_personality','p_23',23,'LIKERT_SCALE','neuroticism','Me cuesta conciliar el sueño cuando estoy preocupado.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'sleep_disturbance', true),
('assess_psych_personality','p_24',24,'LIKERT_SCALE','neuroticism','Me siento deprimido cuando las cosas no salen como espero.',$$[{"text":"Totalmente en desacuerdo","value":5},{"text":"En desacuerdo","value":4},{"text":"Neutral","value":3},{"text":"De acuerdo","value":2},{"text":"Totalmente de acuerdo","value":1}]$$, 'mood_swings', true),
('assess_psych_personality','p_25',25,'LIKERT_SCALE','neuroticism','Mantenerme calmado bajo presión es algo que practico y mejoro.',$$[{"text":"Totalmente en desacuerdo","value":1},{"text":"En desacuerdo","value":2},{"text":"Neutral","value":3},{"text":"De acuerdo","value":4},{"text":"Totalmente de acuerdo","value":5}]$$, 'emotional_stability', false);

-- 3. JUICIO SITUACIONAL SJT
INSERT INTO "Assessment" ("id", "name", "category", "description", "timeLimitMinutes", "targetRoles", "isActive", "createdAt", "updatedAt")
VALUES ('assess_behav_sjt', 'Juicio Situacional (SJT)', 'BEHAVIORAL',
'Qué mide: Evalúa cómo respondes ante situaciones laborales realistas con múltiples opciones. Mide leadership, trabajo en equipo, resolución de conflictos, ética profesional y manejo de presión. Cada opción tiene un peso diferente que refleja la efectividad de la respuesta.',
12, ARRAY['manager','operations','sales','marketing','all'], true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "Question" ("assessmentId", "questionId", "order", "type", "dimension", "text", "scenario", "options", "subDimension")
VALUES
-- LEADERSHIP (3)
('assess_behav_sjt','sjt_01',1,'SCENARIO','leadership','Tu equipo tiene dos desarrolladores en conflicto sobre la arquitectura de un proyecto crítico. La fecha límite es en 2 semanas.','¿Qué harías?',$$[{"text":"Decides tu postura y la impones como líder","value":1},{"text":"Organizas sesión de brainstorming para que encuentren solución conjunta","value":5},{"text":"Dejas que resuelvan solos para que asuman responsabilidad","value":2},{"text":"Escalas al director de ingeniería para que decida","value":3}]$$, 'conflict_resolution'),
('assess_behav_sjt','sjt_02',2,'SCENARIO','leadership','Tu equipo no alcanza metas de rendimiento. Dos miembros clave tienen problemas de adicción.','¿Qué harías?',$$[{"text":"Confrontas directamente y los reemplazas","value":1},{"text":"Organizas reunión y aplicas políticas de rehabilitación","value":5},{"text":"Informas a la empresa para que busque ayuda profesional","value":3},{"text":"Ignoras el problema y esperas que se resuelva","value":2}]$$, 'performance_management'),
('assess_behav_sjt','sjt_03',3,'SCENARIO','leadership','Eres responsable de una fusión entre dos equipos con diferentes culturas. Uno es muy formal y el otro muy informal.','¿Qué harías?',$$[{"text":"Impones la cultura formal para mantener profesionalismo","value":1},{"text":"Identificas los mejores aspectos de ambas culturas y los integras","value":5},{"text":"Dejas que cada equipo mantenga su cultura","value":2},{"text":"Escalas al CEO para que decida la cultura","value":3}]$$, 'culture_integration'),
-- TEAMWORK (2)
('assess_behav_sjt','sjt_04',4,'SCENARIO','teamwork','Un compañero de equipo tiene problemas personales graves y su rendimiento ha bajado. El proyecto depende de su entrega.','¿Qué harías?',$$[{"text":"Organizas reunión para ofrecer apoyo y ajustar cargas","value":5},{"text":"Reportas la situación a tu manager","value":3},{"text":"Tomas sus tareas sin preguntar","value":1},{"text":"Ignoras la situación y esperas que se resuelva","value":2}]$$, 'peer_support'),
('assess_behav_sjt','sjt_05',5,'SCENARIO','teamwork','Estás en un equipo donde hay socios competitivos y poco colaboradores. Sientes que el trabajo no avanza.','¿Qué harías?',$$[{"text":"Comunicas el problema al manager y propones team building","value":5},{"text":"Tratas de ser más amable con cada uno individualmente","value":3},{"text":"Mientes a otros sobre el avance para "presionar" al equipo","value":1},{"text":"Te retiras del equipo para evitar el conflicto","value":2}]$$, 'collaboration_building'),
-- CONFLICT RESOLUTION (2)
('assess_behav_sjt','sjt_06',6,'SCENARIO','conflict_resolution','Un cliente importante está muy enojado porque un producto falló. Exige una disculpa pública.','¿Qué harías?',$$[{"text":"Concédes la disculpa inmediata sin investigar","value":1},{"text":"Investigas el problema, haces seguimiento personalizado y ofreces solución","value":5},{"text":"Rechazas la disculpa porque no fue tu culpa","value":3},{"text":"Escalas a legal para evitar responsabilidad","value":2}]$$, 'customer_management'),
('assess_behav_sjt','sjt_07',7,'SCENARIO','conflict_resolution','En una reunión, un colega ataca personalmente a otro miembro. El ambiente se vuelve hostil.','¿Qué harías?',$$[{"text":"Defiendes al atacado respondiendo con la misma intensidad","value":1},{"text":"Intervienes calmadamente para redirigir la discusión al tema profesional","value":5},{"text":"Ignoras el ataque y tomas notas","value":3},{"text":"Reportas el incidente a recursos humanos","value":2}]$$, 'de_escalation'),
-- ETHICS (2)
('assess_behav_sjt','sjt_08',8,'SCENARIO','ethics','Descubres que un compañero ha usado información confidencial de un cliente para beneficio personal. Lo sabes por segunda mano, sin prueba directa.','¿Qué harías?',$$[{"text":"Reportas al compañero si tienes evidencia","value":5},{"text":"Lo confrontas directamente para que se corrija","value":3},{"text":"Lo ignoras porque no tienes prueba directa","value":1},{"text":"Escalas sin investigación y sin evidencia","value":2}]$$, 'whistleblower'),
('assess_behav_sjt','sjt_09',9,'SCENARIO','ethics','Eres manager y un cliente te ofrece dinero para priorizar su proyecto sobre otros clientes.','¿Qué harías?',$$[{"text":"Aceptas pero lo oculto a la empresa","value":1},{"text":"Rechazas la oferta y reportas la situación","value":5},{"text":"Aceptas pero tratas a todos por igual","value":2},{"text":"No respondes al cliente pero mantienes la prioridad","value":3}]$$, 'bribery'),
-- PRESSURE (1)
('assess_behav_sjt','sjt_10',10,'SCENARIO','pressure_management','Tienes una presentación importante en 1 hora, pero un problema técnico crítico aparece y no hay laptop de respaldo.','¿Qué harías?',$$[{"text":"Cancelas la presentación y te vas","value":1},{"text":"Usas tu laptop personal y preparas versión simplificada","value":5},{"text":"Pides a alguien que te preste su equipo","value":2},{"text":"Presentas solo con tu smartphone","value":3}]$$, 'crisis_response');

-- 4. EVALUACIÓN TÉCNICA
INSERT INTO "Assessment" ("id", "name", "category", "description", "timeLimitMinutes", "targetRoles", "isActive", "createdAt", "updatedAt")
VALUES ('assess_tech_dev', 'Evaluación Técnica - Desarrollo', 'TECHNICAL',
'Qué mide: Cubre conceptos fundamentales de desarrollo de software: algoritmos y estructuras de datos, arquitectura de sistemas, bases de datos y buenas prácticas de código. No prueba lenguajes específicos sino conceptos universales que aplican a cualquier stack.',
12, ARRAY['technology','developer','engineer','analyst'], true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "Question" ("assessmentId", "questionId", "order", "type", "dimension", "text", "options", "subDimension")
VALUES
-- ARCHITECTURE (3)
('assess_tech_dev','t_01',1,'MULTIPLE_CHOICE','architecture','¿Cuál patrón de diseño es más adecuado para crear una única instancia de una clase que gestiona recursos compartidos?',$$[{"text":"Factory","value":0},{"text":"Singleton","value":1},{"text":"Observer","value":0},{"text":"Strategy","value":0}]$$, 'design_patterns'),
('assess_tech_dev','t_02',2,'MULTIPLE_CHOICE','architecture','¿Cuál es la diferencia principal entre LEFT JOIN e INNER JOIN?',$$[{"text":"LEFT JOIN retorna todo de la tabla izquierda con NULL si hay match","value":1},{"text":"INNER JOIN retorna filas de ambas con match","value":1},{"text":"Son iguales","value":0},{"text":"LEFT JOIN es más rápido","value":0}]$$, 'joins'),
('assess_tech_dev','t_03',3,'MULTIPLE_CHOICE','architecture','¿Qué principio SOLID se aplica cuando una clase tiene una única responsabilidad?',$$[{"text":"Single Responsibility Principle (SRP)","value":1},{"text":"Open-Closed Principle","value":0},{"text":"Liskov Substitution Principle","value":0},{"text":"Interface Segregation","value":0}]$$, 'solid_principles'),
-- DATABASES (3)
('assess_tech_dev','t_04',4,'MULTIPLE_CHOICE','databases','¿Cuál es la complejidad temporal de acceder a un elemento por índice en un array?',$$[{"text":"O(1)","value":1},{"text":"O(n)","value":0},{"text":"O(log n)","value":0},{"text":"O(n²)","value":0}]$$, 'arrays'),
('assess_tech_dev','t_05',5,'MULTIPLE_CHOICE','databases','¿Qué tipo de índice es más eficiente para consultas de rango?',$$[{"text":"B-Tree (árbol balanceado)","value":1},{"text":"Hash Index","value":0},{"text":"Bitmap Index","value":0},{"text":"No hay diferencia","value":0}]$$, 'indexing'),
('assess_tech_dev','t_06',6,'MULTIPLE_CHOICE','databases','¿Cuál es la ventaja principal de MongoDB sobre SQL?',$$[{"text":"Escalabilidad horizontal flexible y esquema flexible","value":1},{"text":"Siempre más rápido","value":0},{"text":"Soporta transacciones ACID","value":0},{"text":"Más seguro","value":0}]$$, 'nosql_vs_sql'),
-- ALGORITHMS (3)
('assess_tech_dev','t_07',7,'MULTIPLE_CHOICE','algorithms','¿Cuál es la complejidad temporal de Merge Sort en el peor caso?',$$[{"text":"O(n log n)","value":1},{"text":"O(n²)","value":0},{"text":"O(n)","value":0},{"text":"O(log n)","value":0}]$$, 'sorting'),
('assess_tech_dev','t_08',8,'MULTIPLE_CHOICE','algorithms','Dado un array ordenado, ¿cuál algoritmo de búsqueda tiene mejor complejidad?',$$[{"text":"Binary Search: O(log n)","value":1},{"text":"Linear Search: O(n)","value":0},{"text":"Ambos son iguales","value":0},{"text":"Depende del lenguaje","value":0}]$$, 'search'),
('assess_tech_dev','t_09',9,'MULTIPLE_CHOICE','algorithms','¿Qué estructura de datos usa FIFO (First In, First Out)?',$$[{"text":"Queue (Cola)","value":1},{"text":"Stack (Pila)","value":0},{"text":"Array","value":0},{"text":"Hash Table","value":0}]$$, 'data_structures'),
-- CODE QUALITY (3)
('assess_tech_dev','t_10',10,'MULTIPLE_CHOICE','code_quality','¿Cuál es el propósito principal de los tests automatizados?',$$[{"text":"Detectar bugs antes de producción y facilitar refactoring","value":1},{"text":"Aumentar tiempo de desarrollo","value":0},{"text":"Reemplazar código manual","value":0},{"text":"Eliminar bugs completamente","value":0}]$$, 'testing'),
('assess_tech_dev','t_11',11,'MULTIPLE_CHOICE','code_quality','¿Qué es DRY en desarrollo de software?',$$[{"text":"Don''t Repeat Yourself - evitar código duplicado","value":1},{"text":"Do Repeat Yourself","value":0},{"text":"Design Review Yearly","value":0},{"text":"Data Recovery Y","value":0}]$$, 'dry'),
('assess_tech_dev','t_12',12,'MULTIPLE_CHOICE','code_quality','¿Cuál es la diferencia principal entre TDD y desarrollo tradicional?',$$[{"text":"En TDD se escriben tests primero antes del código","value":1},{"text":"No hay diferencia","value":0},{"text":"TDD es más lento siempre","value":0},{"text":"Solo se usa para pequeños proyectos","value":0}]$$, 'tdd');

-- ============================================================
-- ✅ TOTAL: 61 preguntas en 4 evaluaciones
-- ============================================================
